language: php

php:
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

notifications:
email:
  recipients:
    - bardoqi@gmail.com
  on_success: always
  on_failure: always

