language: php

php:
  - 7.2

env:
  - LARAVEL_VERSION=5.8.*
  - LARAVEL_VERSION=6.*
  - LARAVEL_VERSION=7.*
  - LARAVEL_VERSION=8.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;
  - composer dump-autoload

script:
  - ./vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
email:
  recipients:
    - bardoqi@gmail.com
  on_success: always
  on_failure: always








